apiVersion: batch/v1
kind: Job
metadata:
  name: javaapp
spec:
  ttlSecondsAfterFinished: {{ .Values.ttlSecondsAfterFinished }}
  template:
    spec:
      containers:
      - name: javaapp
        image: {{ .Values.container.image }}:{{ .Values.container.tag }}
      restartPolicy: {{ .Values.restart }}