version: '3.9'

services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    ports: ["8080:8080"]
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  agent:
    build: ./
    image: jenkins-agent


volumes:
  jenkins_data:
