apiVersion: batch/v1
kind: Job
metadata:
  name: javaapp-job
spec:
  ttlSecondsAfterFinished: 5
  template:
    spec:
      containers:
      - name: javaapp
        image: orya0801/javaapp:$BUILD_NUMBER
      restartPolicy: Never